name: Build & publish OXO images

on:
  push:
    branches: [ "dev", "stable" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push OXO Docker image
        run: |
          docker build -t ghcr.io/ebispot/oxo-loader:${{ github.sha }} -f ./oxo-loader/Dockerfile .
          docker build -t ghcr.io/ebispot/oxo-indexer:${{ github.sha }} -f ./oxo-indexer/Dockerfile .
          docker build -t ghcr.io/ebispot/oxo-web:${{ github.sha }} -f ./oxo-web/Dockerfile .
          docker tag ghcr.io/ebispot/oxo-loader:${{ github.sha }} ghcr.io/ebispot/oxo-loader:${{ github.ref_name }}
          docker tag ghcr.io/ebispot/oxo-indexer:${{ github.sha }} ghcr.io/ebispot/oxo-indexer:${{ github.ref_name }}
          docker tag ghcr.io/ebispot/oxo-web:${{ github.sha }} ghcr.io/ebispot/oxo-web:${{ github.ref_name }}
          docker push --all-tags ghcr.io/ebispot/oxo-loader
          docker push --all-tags ghcr.io/ebispot/oxo-indexer
          docker push --all-tags ghcr.io/ebispot/oxo-web
